### ISSUE TITLE
openai update breaks extention's functionality by crashing the front end

### ISSUE THREAD

**Issue by nekohacker591** [Beat-YT/ChatGPT-Moderation-Blocker#14]
![image](https://github.com/Beat-YT/ChatGPT-Moderation-Blocker/assets/73713314/35e4bf3b-f634-41e7-8dc2-243a322ec065)

[chat.openai.com-1699561722847.log](https://github.com/Beat-YT/ChatGPT-Moderation-Blocker/files/13312521/chat.openai.com-1699561722847.log)

`Unchecked runtime.lastError: The message port closed before a response was received.
Unchecked runtime.lastError: The message port closed before a response was received.
Unchecked runtime.lastError: The message port closed before a response was received.
Unchecked runtime.lastError: The message port closed before a response was received.
Unchecked runtime.lastError: The message port closed before a response was received.
Unchecked runtime.lastError: The message port closed before a response was received.
Unchecked runtime.lastError: The message port closed before a response was received.
Unchecked runtime.lastError: The message port closed before a response was received.
Unchecked runtime.lastError: The message port closed before a response was received.
Unchecked runtime.lastError: The message port closed before a response was received.
Unchecked runtime.lastError: The message port closed before a response was received.
Unchecked runtime.lastError: The message port closed before a response was received.
Unchecked runtime.lastError: The message port closed before a response was received.
chat.openai.com/:1 Access to fetch at 'https://chatgpt.com/status' from origin 'https://chat.openai.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
modapi-disabler.js:112 
        
        
       GET https://chatgpt.com/status net::ERR_FAILED 302 (Found)
window.fetch @ modapi-disabler.js:112
(anonymous) @ _app-61a3c1ac813ae500.js:21
ea @ _app-61a3c1ac813ae500.js:21
(anonymous) @ [[...default]]-4793b0da94f95a5c.js:1
uI @ framework-10a404587b40544b.js:9
oU @ framework-10a404587b40544b.js:9
oC @ framework-10a404587b40544b.js:9
r4 @ framework-10a404587b40544b.js:9
(anonymous) @ framework-10a404587b40544b.js:9
oI @ framework-10a404587b40544b.js:9
oS @ framework-10a404587b40544b.js:9
x @ framework-10a404587b40544b.js:33
T @ framework-10a404587b40544b.js:33
Error with Permissions-Policy header: Unrecognized feature: 'document-domain'.
content.js:431 Unable to check top-level optout: Failed to read a named property 'document' from 'Window': Blocked a frame with origin "https://tcr9i.chat.openai.com" from accessing a cross-origin frame.
checkPageOptout @ content.js:431
(anonymous) @ content.js:445
await in (anonymous) (async)
(anonymous) @ content.js:515
(anonymous) @ content.js:517
Show 4 more frames
Show less
_app-61a3c1ac813ae500.js:21 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at uH (https://cdn.oaistatic.com/_next/static/chunks/framework-10a404587b40544b.js:9:84991)
    at uQ (https://cdn.oaistatic.com/_next/static/chunks/framework-10a404587b40544b.js:9:86232)
    at uq (https://cdn.oaistatic.com/_next/static/chunks/framework-10a404587b40544b.js:9:86495)
    at uQ (https://cdn.oaistatic.com/_next/static/chunks/framework-10a404587b40544b.js:9:86382)
    at uq (https://cdn.oaistatic.com/_next/static/chunks/framework-10a404587b40544b.js:9:86692)
    at uQ (https://cdn.oaistatic.com/_next/static/chunks/framework-10a404587b40544b.js:9:86382)
    at uq (https://cdn.oaistatic.com/_next/static/chunks/framework-10a404587b40544b.js:9:86692)
    at uQ (https://cdn.oaistatic.com/_next/static/chunks/framework-10a404587b40544b.js:9:86382)
    at uq (https://cdn.oaistatic.com/_next/static/chunks/framework-10a404587b40544b.js:9:86495)
    at uQ (https://cdn.oaistatic.com/_next/static/chunks/framework-10a404587b40544b.js:9:86382)
ez.<computed> @ _app-61a3c1ac813ae500.js:21
a6 @ framework-10a404587b40544b.js:9
a.componentDidCatch.t.callback @ framework-10a404587b40544b.js:9
lH @ framework-10a404587b40544b.js:9
uY @ framework-10a404587b40544b.js:9
e @ framework-10a404587b40544b.js:9
(anonymous) @ framework-10a404587b40544b.js:9
oI @ framework-10a404587b40544b.js:9
oC @ framework-10a404587b40544b.js:9
r4 @ framework-10a404587b40544b.js:9
(anonymous) @ framework-10a404587b40544b.js:9
_app-61a3c1ac813ae500.js:21 Error: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.
    at ei (_app-61a3c1ac813ae500.js:1:159)
    at ec (_app-61a3c1ac813ae500.js:21:1051516)
    at eu (_app-61a3c1ac813ae500.js:21:1051281)
    at ed (_app-61a3c1ac813ae500.js:21:1050602)
    at ab (framework-10a404587b40544b.js:9:60917)
    at i (framework-10a404587b40544b.js:9:119475)
    at oO (framework-10a404587b40544b.js:9:99114)
    at framework-10a404587b40544b.js:9:98981
    at oF (framework-10a404587b40544b.js:9:98988)
    at ox (framework-10a404587b40544b.js:9:95740)
ez.<computed> @ _app-61a3c1ac813ae500.js:21
a6 @ framework-10a404587b40544b.js:9
a.componentDidCatch.t.callback @ framework-10a404587b40544b.js:9
lH @ framework-10a404587b40544b.js:9
uY @ framework-10a404587b40544b.js:9
e @ framework-10a404587b40544b.js:9
(anonymous) @ framework-10a404587b40544b.js:9
oI @ framework-10a404587b40544b.js:9
oC @ framework-10a404587b40544b.js:9
r4 @ framework-10a404587b40544b.js:9
(anonymous) @ framework-10a404587b40544b.js:9
_app-61a3c1ac813ae500.js:21 Error: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.
    at ei (_app-61a3c1ac813ae500.js:1:159)
    at ec (_app-61a3c1ac813ae500.js:21:1051516)
    at eu (_app-61a3c1ac813ae500.js:21:1051281)
    at ed (_app-61a3c1ac813ae500.js:21:1050602)
    at ab (framework-10a404587b40544b.js:9:60917)
    at i (framework-10a404587b40544b.js:9:119475)
    at oO (framework-10a404587b40544b.js:9:99114)
    at framework-10a404587b40544b.js:9:98981
    at oF (framework-10a404587b40544b.js:9:98988)
    at ox (framework-10a404587b40544b.js:9:95740)
ez.<computed> @ _app-61a3c1ac813ae500.js:21
ei @ main-2c03450a19a7bc03.js:1
fn @ main-2c03450a19a7bc03.js:1
value @ main-2c03450a19a7bc03.js:1
a.componentDidCatch.t.callback @ framework-10a404587b40544b.js:9
lH @ framework-10a404587b40544b.js:9
uY @ framework-10a404587b40544b.js:9
e @ framework-10a404587b40544b.js:9
(anonymous) @ framework-10a404587b40544b.js:9
oI @ framework-10a404587b40544b.js:9
oC @ framework-10a404587b40544b.js:9
r4 @ framework-10a404587b40544b.js:9
(anonymous) @ framework-10a404587b40544b.js:9
_app-61a3c1ac813ae500.js:21 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
ez.<computed> @ _app-61a3c1ac813ae500.js:21
ei @ main-2c03450a19a7bc03.js:1
fn @ main-2c03450a19a7bc03.js:1
value @ main-2c03450a19a7bc03.js:1
a.componentDidCatch.t.callback @ framework-10a404587b40544b.js:9
lH @ framework-10a404587b40544b.js:9
uY @ framework-10a404587b40544b.js:9
e @ framework-10a404587b40544b.js:9
(anonymous) @ framework-10a404587b40544b.js:9
oI @ framework-10a404587b40544b.js:9
oC @ framework-10a404587b40544b.js:9
r4 @ framework-10a404587b40544b.js:9
(anonymous) @ framework-10a404587b40544b.js:9
_app-61a3c1ac813ae500.js:21 Error: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.
    at ei (_app-61a3c1ac813ae500.js:1:159)
    at ec (_app-61a3c1ac813ae500.js:21:1051516)
    at eu (_app-61a3c1ac813ae500.js:21:1051281)
    at ed (_app-61a3c1ac813ae500.js:21:1050602)
    at ab (framework-10a404587b40544b.js:9:60917)
    at i (framework-10a404587b40544b.js:9:119475)
    at oO (framework-10a404587b40544b.js:9:99114)
    at framework-10a404587b40544b.js:9:98981
    at oF (framework-10a404587b40544b.js:9:98988)
    at ox (framework-10a404587b40544b.js:9:95740)
ez.<computed> @ _app-61a3c1ac813ae500.js:21
a6 @ framework-10a404587b40544b.js:9
a.componentDidCatch.t.callback @ framework-10a404587b40544b.js:9
lH @ framework-10a404587b40544b.js:9
uY @ framework-10a404587b40544b.js:9
e @ framework-10a404587b40544b.js:9
(anonymous) @ framework-10a404587b40544b.js:9
oI @ framework-10a404587b40544b.js:9
oC @ framework-10a404587b40544b.js:9
r4 @ framework-10a404587b40544b.js:9
(anonymous) @ framework-10a404587b40544b.js:9
_app-61a3c1ac813ae500.js:21 Error: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.
    at ei (_app-61a3c1ac813ae500.js:1:159)
    at ec (_app-61a3c1ac813ae500.js:21:1051516)
    at eu (_app-61a3c1ac813ae500.js:21:1051281)
    at ed (_app-61a3c1ac813ae500.js:21:1050602)
    at ab (framework-10a404587b40544b.js:9:60917)
    at i (framework-10a404587b40544b.js:9:119475)
    at oO (framework-10a404587b40544b.js:9:99114)
    at framework-10a404587b40544b.js:9:98981
    at oF (framework-10a404587b40544b.js:9:98988)
    at ox (framework-10a404587b40544b.js:9:95740)
ez.<computed> @ _app-61a3c1ac813ae500.js:21
ei @ main-2c03450a19a7bc03.js:1
fn @ main-2c03450a19a7bc03.js:1
value @ main-2c03450a19a7bc03.js:1
a.componentDidCatch.t.callback @ framework-10a404587b40544b.js:9
lH @ framework-10a404587b40544b.js:9
uY @ framework-10a404587b40544b.js:9
e @ framework-10a404587b40544b.js:9
(anonymous) @ framework-10a404587b40544b.js:9
oI @ framework-10a404587b40544b.js:9
oC @ framework-10a404587b40544b.js:9
r4 @ framework-10a404587b40544b.js:9
(anonymous) @ framework-10a404587b40544b.js:9
_app-61a3c1ac813ae500.js:21 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
ez.<computed> @ _app-61a3c1ac813ae500.js:21
ei @ main-2c03450a19a7bc03.js:1
fn @ main-2c03450a19a7bc03.js:1
value @ main-2c03450a19a7bc03.js:1
a.componentDidCatch.t.callback @ framework-10a404587b40544b.js:9
lH @ framework-10a404587b40544b.js:9
uY @ framework-10a404587b40544b.js:9
e @ framework-10a404587b40544b.js:9
(anonymous) @ framework-10a404587b40544b.js:9
oI @ framework-10a404587b40544b.js:9
oC @ framework-10a404587b40544b.js:9
r4 @ framework-10a404587b40544b.js:9
(anonymous) @ framework-10a404587b40544b.js:9
_app-61a3c1ac813ae500.js:21 Error rendering page:  Error: Cancel rendering route
    at s (main-2c03450a19a7bc03.js:1:11817)
    at main-2c03450a19a7bc03.js:1:11757
    at new Promise (<anonymous>)
    at eh (main-2c03450a19a7bc03.js:1:11728)
    at main-2c03450a19a7bc03.js:1:10227
ez.<computed> @ _app-61a3c1ac813ae500.js:21
(anonymous) @ main-2c03450a19a7bc03.js:1
Promise.catch (async)
fn @ main-2c03450a19a7bc03.js:1
value @ main-2c03450a19a7bc03.js:1
a.componentDidCatch.t.callback @ framework-10a404587b40544b.js:9
lH @ framework-10a404587b40544b.js:9
uY @ framework-10a404587b40544b.js:9
e @ framework-10a404587b40544b.js:9
(anonymous) @ framework-10a404587b40544b.js:9
oI @ framework-10a404587b40544b.js:9
oC @ framework-10a404587b40544b.js:9
r4 @ framework-10a404587b40544b.js:9
(anonymous) @ framework-10a404587b40544b.js:9
modapi-disabler.js:24 
        
        
       POST https://chat.openai.com/backend-api/conversation 422 (Unprocessable Content)
window.fetch @ modapi-disabler.js:24
(anonymous) @ _app-61a3c1ac813ae500.js:21
ea @ _app-61a3c1ac813ae500.js:21
y @ chatGPTFetchInterceptor.js:1
await in y (async)
eM @ _app-61a3c1ac813ae500.js:21
(anonymous) @ _app-61a3c1ac813ae500.js:21
eT @ _app-61a3c1ac813ae500.js:21
(anonymous) @ _app-61a3c1ac813ae500.js:21
Y.with @ _app-61a3c1ac813ae500.js:1
Y.with @ _app-61a3c1ac813ae500.js:1
(anonymous) @ _app-61a3c1ac813ae500.js:21
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
n @ main-2c03450a19a7bc03.js:1
u @ main-2c03450a19a7bc03.js:1
Promise.then (async)
n @ main-2c03450a19a7bc03.js:1
u @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ _app-61a3c1ac813ae500.js:21
(anonymous) @ _app-61a3c1ac813ae500.js:21
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
n @ main-2c03450a19a7bc03.js:1
u @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
Y.publicApiCompletionStream @ _app-61a3c1ac813ae500.js:21
(anonymous) @ 2782-2355eef993065a27.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
n @ main-2c03450a19a7bc03.js:1
u @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ 2782-2355eef993065a27.js:1
(anonymous) @ 2782-2355eef993065a27.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
n @ main-2c03450a19a7bc03.js:1
u @ main-2c03450a19a7bc03.js:1
Promise.then (async)
n @ main-2c03450a19a7bc03.js:1
u @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ 2782-2355eef993065a27.js:1
(anonymous) @ 2782-2355eef993065a27.js:1
(anonymous) @ _app-61a3c1ac813ae500.js:21
handler @ _app-61a3c1ac813ae500.js:21
(anonymous) @ _app-61a3c1ac813ae500.js:21
eU @ framework-10a404587b40544b.js:9
eH @ framework-10a404587b40544b.js:9
(anonymous) @ framework-10a404587b40544b.js:9
re @ framework-10a404587b40544b.js:9
rn @ framework-10a404587b40544b.js:9
(anonymous) @ framework-10a404587b40544b.js:9
oP @ framework-10a404587b40544b.js:9
eF @ framework-10a404587b40544b.js:9
ro @ framework-10a404587b40544b.js:9
nU @ framework-10a404587b40544b.js:9
nD @ framework-10a404587b40544b.js:9
_app-61a3c1ac813ae500.js:21 UserError: I'm unable to produce a response
    at _app-61a3c1ac813ae500.js:21:644523
    at main-2c03450a19a7bc03.js:1:115276
    at Object.next (main-2c03450a19a7bc03.js:1:115381)
    at n (main-2c03450a19a7bc03.js:1:104807)
    at u (main-2c03450a19a7bc03.js:1:105004)
ez.<computed> @ _app-61a3c1ac813ae500.js:21
(anonymous) @ 2782-2355eef993065a27.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
n @ main-2c03450a19a7bc03.js:1
u @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ 2782-2355eef993065a27.js:1
onerror @ _app-61a3c1ac813ae500.js:21
eM @ _app-61a3c1ac813ae500.js:21
await in eM (async)
(anonymous) @ _app-61a3c1ac813ae500.js:21
eT @ _app-61a3c1ac813ae500.js:21
(anonymous) @ _app-61a3c1ac813ae500.js:21
Y.with @ _app-61a3c1ac813ae500.js:1
Y.with @ _app-61a3c1ac813ae500.js:1
(anonymous) @ _app-61a3c1ac813ae500.js:21
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
n @ main-2c03450a19a7bc03.js:1
u @ main-2c03450a19a7bc03.js:1
Promise.then (async)
n @ main-2c03450a19a7bc03.js:1
u @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ _app-61a3c1ac813ae500.js:21
(anonymous) @ _app-61a3c1ac813ae500.js:21
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
n @ main-2c03450a19a7bc03.js:1
u @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
Y.publicApiCompletionStream @ _app-61a3c1ac813ae500.js:21
(anonymous) @ 2782-2355eef993065a27.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
n @ main-2c03450a19a7bc03.js:1
u @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ 2782-2355eef993065a27.js:1
(anonymous) @ 2782-2355eef993065a27.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
n @ main-2c03450a19a7bc03.js:1
u @ main-2c03450a19a7bc03.js:1
Promise.then (async)
n @ main-2c03450a19a7bc03.js:1
u @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ main-2c03450a19a7bc03.js:1
(anonymous) @ 2782-2355eef993065a27.js:1
(anonymous) @ 2782-2355eef993065a27.js:1
(anonymous) @ _app-61a3c1ac813ae500.js:21
handler @ _app-61a3c1ac813ae500.js:21
(anonymous) @ _app-61a3c1ac813ae500.js:21
eU @ framework-10a404587b40544b.js:9
eH @ framework-10a404587b40544b.js:9
(anonymous) @ framework-10a404587b40544b.js:9
re @ framework-10a404587b40544b.js:9
rn @ framework-10a404587b40544b.js:9
(anonymous) @ framework-10a404587b40544b.js:9
oP @ framework-10a404587b40544b.js:9
eF @ framework-10a404587b40544b.js:9
ro @ framework-10a404587b40544b.js:9
nU @ framework-10a404587b40544b.js:9
nD @ framework-10a404587b40544b.js:9
chat.openai.com/:1 Access to fetch at 'https://sentry.quillbot.com/api/2/envelope/?sentry_key=3efaa937a1c3287565ae36bf8c826db9&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.73.0' from origin 'https://chat.openai.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
quillbot-content.js:795 
        
        
       POST https://sentry.quillbot.com/api/2/envelope/?sentry_key=3efaa937a1c3287565ae36bf8c826db9&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.73.0 net::ERR_FAILED 503 (Service Unavailable)
(anonymous) @ quillbot-content.js:795
(anonymous) @ quillbot-content.js:795
add @ quillbot-content.js:795
d @ quillbot-content.js:795
_sendEnvelope @ quillbot-content.js:965
_flushOutcomes @ quillbot-content.js:795
(anonymous) @ quillbot-content.js:795
Show 7 more frames
Show less
`

**Comment by Beat-YT** [comment]
Ah shit.
