### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by Reloadddd** [Beat-YT/ChatGPT-Moderation-Blocker#16]
Throws the following error in the console - _app-7dbdbc3310f0a44d.js:26 TypeError: Failed to execute 'getReader' on 'ReadableStream': ReadableStreamDefaultReader constructor can only accept readable streams that are not yet locked to a reader

and doesn't hide the red colored blocked messages. However, those messages show up on refreshing the page

**Comment by Beat-YT** [comment]
I will check.
