### ISSUE TITLE
Stopped Working as of May 15th, 2023

### ISSUE THREAD

**Issue by VinceyG** [Beat-YT/ChatGPT-Moderation-Blocker#2]
From what I can gather now, it removes the warning when reloading the page but as soon as you put in a new prompt they come back. Hopefully you can get this back running soon (:

**Comment by phoenixwarlord** [comment]
it stopped working for me a couple of hours ago too, hopefully there will be a fix soon...

**Comment by MsiCantLiveinreality** [comment]
Same here, eagerly awaiting an update for it.

**Comment by Voids0713** [comment]
In the request body, there is a newly added field "supports_modapi", I am not familiar with the Chrome extension but if you set supports_modapi = false using any tools. Moderation api will not be called internally, for now.

**Comment by virox** [comment]
Would that be possible using an adblocker? Until now, I just blocked the moderations endpoint in ublock.

**Comment by Beat-YT** [comment]
I submitted the update to chrome web store. waiting for approval ..

**Comment by Beat-YT** [comment]
you can head over to release tab and manually download the extension: https://github.com/Beat-YT/ChatGPT-Moderation-Blocker/releases/tag/release-v3

**Comment by Beat-YT** [comment]
Drag and drop the '.crx' extension file onto the Extensions page at chrome://extensions

**Comment by MsiCantLiveinreality** [comment]
![Screenshot 2023-05-16 184840](https://github.com/Beat-YT/ChatGPT-Moderation-Blocker/assets/125337281/7864fa09-78d1-40f1-a4d0-cab93f2f108f)
Forgive me for my ignorance but I can't seem to get rid of this error, I have my developer mode enabled and it still popped up.

**Comment by Beat-YT** [comment]
try downloading the zip and extract it and then add unpacked

**Comment by Beat-YT** [comment]
As this issue is fix, ill be closing the issue.

**Comment by littlebabdlil** [comment]
![image](https://github.com/Beat-YT/ChatGPT-Moderation-Blocker/assets/139635184/fe610dc5-8426-4b69-b2e4-15596cbf47b7)
 what can I do?

**Comment by Beat-YT** [comment]
> ![image](https://user-images.githubusercontent.com/139635184/253744364-fe610dc5-8426-4b69-b2e4-15596cbf47b7.png) what can I do?

unrelated, my extension does not bypass chat gpt integrated filters, but it bypasses the website flagging your requests and its responses.
