### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by Iker2512** [Beat-YT/ChatGPT-Moderation-Blocker#21]
Recently, chat gpt changed its URL. Guess that it could be the problem. For now it's not working

![Captura de pantalla 2024-05-03 233145](https://github.com/Beat-YT/ChatGPT-Moderation-Blocker/assets/168886862/0924e068-cb93-4ed1-b062-8230561c62b1)

**Comment by Beat-YT** [comment]
I have submitted an update to the chrome web store, currently awaiting approval for publication.

**Comment by MoonwalkDelta27** [comment]
The issue persists, even after updating
![image](https://github.com/Beat-YT/ChatGPT-Moderation-Blocker/assets/60715498/2056457e-4d82-4dd5-9f83-40add6c033ea)

**Comment by Beat-YT** [comment]
Fixed in update
