### ISSUE TITLE
supports_modapi is still true.

### ISSUE THREAD

**Issue by Voids0713** [Beat-YT/ChatGPT-Moderation-Blocker#3]
Downloaded and tried installing unpacked, the supports_modapi is still true. I am using v3 should be the correct version.

**Comment by MsiCantLiveinreality** [comment]
> Downloaded and tried installing unpacked, the supports_modapi is still true. I am using v3 should be the correct version.

Same here.

**Comment by Nextovoy** [comment]
And same here for me.

**Comment by Beat-YT** [comment]
Weird, I'll check this out later

**Comment by Beat-YT** [comment]
Very weird, to me, it looks like supports_modapi is completely gone...

![image](https://github.com/Beat-YT/ChatGPT-Moderation-Blocker/assets/66485277/27a4ce1e-ab9c-4302-b721-2e32885853f5)

**Comment by Beat-YT** [comment]
Even tho,  I added a patcher, just in case they decide to re-introduce it.
