### ISSUE TITLE
Update causes website to not load. 

### ISSUE THREAD

**Issue by MsiCantLiveinreality** [Beat-YT/ChatGPT-Moderation-Blocker#4]
I tried the new version of the extension; it causes the website to keep loading. It won't load the previous chats or anything. I tried using it without it and it loaded relatively fine.

**Comment by Beat-YT** [comment]
Please update to release-v3.2

**Comment by MsiCantLiveinreality** [comment]
My apoligies, yes, the website loads fine now ^^ thank you so much for this.

**Comment by Beat-YT** [comment]
Alright!
