### ISSUE TITLE
Doesn't work anymore, answer is not given

### ISSUE THREAD

**Issue by Billarin** [Beat-YT/ChatGPT-Moderation-Blocker#9]
So I just tried it and it doesn't work. I am using the chrome extension and here is what happen when i use chatgpt.
I asked a translation for a chinese novel (it has 18+ content). When using the extension it no longer block the prompt i give to translate the text i give it but it doesn't answer with the translation. the answer box just stay empty no matter how many times i click regenerate answer.

**Comment by Beat-YT** [comment]
fixed
